# Generated by Django 3.0.5 on 2021-02-28 15:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210228_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('trending_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
