# Generated by Django 3.0.5 on 2021-02-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210228_1348'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDetails',
            new_name='Student',
        ),
    ]
