# Generated by Django 3.0.5 on 2021-01-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(default=0, help_text='0: inactive, 1: active, 2: disabled'),
        ),
    ]
