# Generated by Django 3.0.5 on 2021-02-28 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210104_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='type',
            field=models.CharField(default='activate user', help_text='activate user, reset password', max_length=20),
        ),
    ]
