# Generated by Django 3.0.5 on 2021-02-28 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_category_type_university'),
        ('user', '0004_auto_20210228_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('dateOfBirth', models.DateTimeField()),
                ('gender', models.CharField(max_length=10)),
                ('activeProjects', models.PositiveIntegerField(default=0)),
                ('about', models.TextField()),
                ('facebook', models.TextField()),
                ('resumeUrl', models.TextField()),
                ('linkedIn', models.TextField()),
                ('gmail', models.TextField()),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.University')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.Category')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.StudentDetails')),
            ],
        ),
    ]
