# Generated by Django 3.0.5 on 2021-05-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210503_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='facebook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gmail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedIn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
