# Generated by Django 3.0.5 on 2021-05-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210503_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='https://fyp-images-narvitaa.s3.ap-south-1.amazonaws.com/default_avatar.png'),
        ),
    ]
