# Generated by Django 3.0.5 on 2021-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210505_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='twitter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
