# Generated by Django 3.0.5 on 2021-05-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_student_twitter'),
        ('user', '0006_auto_20210505_1843'),
    ]

    operations = [
    ]
