# Generated by Django 3.0.5 on 2021-03-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_auto_20210228_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='type',
            field=models.CharField(help_text='public/private', max_length=20),
        ),
    ]
